# Generated by Django 3.2.9 on 2021-11-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Package_name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='0', upload_to='images')),
                ('desc', models.CharField(max_length=6000)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
