# Generated by Django 3.2.9 on 2021-11-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0002_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('destination', models.CharField(default='', max_length=100)),
                ('departure', models.CharField(default='', max_length=100)),
                ('number_of_guests', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('trip_date', models.DateTimeField(auto_created='')),
                ('desc', models.CharField(default='', max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
