# Generated by Django 3.2.9 on 2021-11-26 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0003_auto_20211126_2252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Bookinghandle',
        ),
    ]
