# Generated by Django 3.2.9 on 2021-11-26 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0004_rename_booking_bookinghandle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookinghandle',
            new_name='Booking',
        ),
    ]
