# Generated by Django 3.2.9 on 2021-11-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0005_rename_bookinghandle_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tour_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
