# Generated by Django 3.2.9 on 2021-11-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0006_contact_tour_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
