# Generated by Django 3.2.9 on 2021-12-02 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0007_booking_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='destination',
        ),
    ]
