# Generated by Django 3.2.9 on 2021-12-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0008_remove_booking_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.CharField(default='', max_length=100),
        ),
    ]
